version: '3.3'

services:
  psql-eshop:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'ESHOPEE'
      POSTGRES_USER: 'userdatabase'
      POSTGRES_PASSWORD: 'passdatabase'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init-files:/docker-entrypoint-initdb.d
    networks:
      - postgres-pgadmin-network

  pgadm-eshop:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgpass
    ports:
      - "8000:80"
    networks:
      - postgres-pgadmin-network

networks:
  postgres-pgadmin-network:

volumes:
  postgres-data: